### ISSUE TITLE
BUG: Heroku App Crashing

### ISSUE THREAD

**Issue by antonhibl** [Ashutosh00710/github-readme-activity-graph#115]
I tried to follow the steps to set up my own Heroku instance but it seems like the build might be buggy because after following all the instructions, the app is inaccessible and my application logs show it crashes on startup.

**To Reproduce**
I followed the steps to set up my own Heroku instance, however, after all of the steps were finished I can't access my application at the URL https://git-activity-graph.herokuapp.com/ and the application logs show the app crashes on startup.

**Expected behavior**
I expected the app to run and let me access it at the requested web page and in my GitHub config.

This is what I could gather from my application logs in Heroku:
```
2022-03-24T15:17:07.167220+00:00 app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

2022-03-24T15:17:07.167220+00:00 app[web.1]:     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1059:12)

2022-03-24T15:17:07.167221+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)

2022-03-24T15:17:07.167221+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

2022-03-24T15:17:07.167221+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)

2022-03-24T15:17:07.176338+00:00 app[web.1]: [31m[nodemon] app crashed - waiting for file changes before starting...[39m

2022-03-24T15:18:02.431338+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

2022-03-24T15:18:02.552685+00:00 heroku[web.1]: Stopping process with SIGKILL

2022-03-24T15:18:02.731745+00:00 heroku[web.1]: Process exited with status 137

2022-03-24T15:18:02.803080+00:00 heroku[web.1]: State changed from starting to crashed

2022-03-24T15:30:52.022530+00:00 heroku[web.1]: State changed from crashed to starting

2022-03-24T15:30:55.030398+00:00 heroku[web.1]: Starting process with command `npm start`

2022-03-24T15:30:56.239709+00:00 app[web.1]: 

2022-03-24T15:30:56.239723+00:00 app[web.1]: > github-readme-activity-graph@1.0.0 start

2022-03-24T15:30:56.239724+00:00 app[web.1]: > nodemon src/main.ts

2022-03-24T15:30:56.239724+00:00 app[web.1]: 

2022-03-24T15:30:56.403662+00:00 app[web.1]: [33m[nodemon] 2.0.7[39m

2022-03-24T15:30:56.404654+00:00 app[web.1]: [33m[nodemon] to restart at any time, enter `rs`[39m

2022-03-24T15:30:56.405089+00:00 app[web.1]: [33m[nodemon] watching path(s): *.*[39m

2022-03-24T15:30:56.405091+00:00 app[web.1]: [33m[nodemon] watching extensions: ts,json[39m

2022-03-24T15:30:56.405510+00:00 app[web.1]: [32m[nodemon] starting `ts-node src/main.ts`[39m

2022-03-24T15:31:00.963552+00:00 app[web.1]: 

2022-03-24T15:31:00.964077+00:00 app[web.1]: /app/node_modules/ts-node/src/index.ts:513

2022-03-24T15:31:00.964079+00:00 app[web.1]:     return new TSError(diagnosticText, diagnosticCodes)

2022-03-24T15:31:00.964079+00:00 app[web.1]:            ^

2022-03-24T15:31:00.964184+00:00 app[web.1]: TSError: ⨯ Unable to compile TypeScript:

2022-03-24T15:31:00.964186+00:00 app[web.1]: src/GraphCards.ts(45,13): error TS6133: 'getContrubutionDates' is declared but its value is never read.

2022-03-24T15:31:00.964186+00:00 app[web.1]: 

2022-03-24T15:31:00.964187+00:00 app[web.1]:     at createTSError (/app/node_modules/ts-node/src/index.ts:513:12)

2022-03-24T15:31:00.964188+00:00 app[web.1]:     at reportTSError (/app/node_modules/ts-node/src/index.ts:517:19)

2022-03-24T15:31:00.964188+00:00 app[web.1]:     at getOutput (/app/node_modules/ts-node/src/index.ts:752:36)

2022-03-24T15:31:00.964188+00:00 app[web.1]:     at Object.compile (/app/node_modules/ts-node/src/index.ts:968:32)

2022-03-24T15:31:00.964188+00:00 app[web.1]:     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1056:42)

2022-03-24T15:31:00.964189+00:00 app[web.1]:     at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

2022-03-24T15:31:00.964189+00:00 app[web.1]:     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1059:12)

2022-03-24T15:31:00.964190+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)

2022-03-24T15:31:00.964190+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

2022-03-24T15:31:00.964190+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)

2022-03-24T15:31:00.976839+00:00 app[web.1]: [31m[nodemon] app crashed - waiting for file changes before starting...[39m
2022-03-24T15:33:00.000792+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

2022-03-24T15:33:00.083121+00:00 heroku[web.1]: Stopping process with SIGKILL

2022-03-24T15:33:00.117669+00:00 app[web.1]: Error waiting for process to terminate: No child processes

2022-03-24T15:33:00.265599+00:00 heroku[web.1]: Process exited with status 22

2022-03-24T15:33:00.387265+00:00 heroku[web.1]: State changed from starting to crashed
```

**Desktop:**
 - OS: macOS Big Sur v11.18.1
 - Browser: Firefox
 - Version: 99.0b1

**Comment by Ashutosh00710** [comment]
@antonhibl try now

**Comment by antonhibl** [comment]
@Ashutosh00710 fixed, thanks!
